### ISSUE TITLE
broken pipe error when acknowledging alert from opsgenie to jira using OEC

### ISSUE THREAD

**Issue by DPatrickBoyd** [opsgenie/oec-scripts#41]
Here is the error that I get, please note that I have altered the script to not enforce certs when making the requests/updates, but that is the only difference.

---------------------------

ecuted [addCommentToIssue] action via OEC[integrationId: ****** integrationType: Jira] with errors. Reason: Err: exit status 120, Stderr: --- Logging error --- Traceback (most recent call last): File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit self.flush() File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush self.stream.flush() BrokenPipeError: [Errno 32] Broken pipe Call stack: File "/home/opsgenie/oec/scripts/actionExecutor.py", line 215, in <module> main() File "/home/opsgenie/oec/scripts/actionExecutor.py", line 93, in main logging.debug("Username: " + str(username)) Message: 'Username: *******' Arguments: () --- Logging error --- Traceback (most recent call last): File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit self.flush() File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush self.stream.flush() BrokenPipeError: [Errno 32] Broken pipe Call stack: File "/home/opsgenie/oec/scripts/actionExecutor.py", line 215, in <module> main() File "/home/opsgenie/oec/scripts/actionExecutor.py", line 94, in main logging.debug("Project Key: " + str(project_key)) Message: 'Project Key: ****' Arguments: () --- Logging error --- Traceback (most recent call last): File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit self.flush() File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush self.stream.flush() BrokenPipeError: [Errno 32] Broken pipe Call stack: File "/home/opsgenie/oec/scripts/actionExecutor.py", line 215, in <module> main() File "/home/opsgenie/oec/scripts/actionExecutor.py", line 95, in main logging.debug("Issue Type: " + str(issue_type_name)) Message: 'Issue Type: Incident' Arguments: () --- Logging error --- Traceback (most recent call last): File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit self.flush() File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush self.stream.flush() BrokenPipeError: [Errno 32] Broken pipe Call stack: File "/home/opsgenie/oec/scripts/actionExecutor.py", line 215, in <module> main() File "/home/opsgenie/oec/scripts/actionExecutor.py", line 96, in main logging.debug("Issue Key: " + str(issue_key)) Message: 'Issue Key: *****' Arguments: () --- Logging error --- Traceback (most recent call last): File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit self.flush() File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush self.stream.flush() BrokenPipeError: [Errno 32] Broken pipe Call stack: File "/home/opsgenie/oec/scripts/actionExecutor.py", line 215, in <module> main() File "/home/opsgenie/oec/scripts/actionExecutor.py", line 167, in main logging.debug(str(content_params)) Message: '{\'body\': \'[Opsgenie] ***** closed alert: "last try for Friday" https://opsg.in/a/t/tandemdiabetes/375\'}' Arguments: () --- Logging error --- Traceback (most recent call last): File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit self.flush() File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush self.stream.flush() BrokenPipeError: [Errno 32] Broken pipe Call stack: File "/home/opsgenie/oec/scripts/actionExecutor.py", line 215, in <module> main() File "/home/opsgenie/oec/scripts/actionExecutor.py", line 169, in main timeout=timeout, verify=False) File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post return request('post', url, data=data, json=json, **kwargs) File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request return session.request(method=method, url=url, **kwargs) File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request resp = self.send(prep, **send_kwargs) File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send r = adapter.send(request, **kwargs) File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send timeout=timeout File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 589, in urlopen conn = self._get_conn(timeout=pool_timeout) File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 251, in _get_conn return conn or self._new_conn() File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 826, in _new_conn self.num_connections, self.host) Message: 'Starting new HTTPS connection (%d): %s' Arguments: (1, 'jira.tandemdiabetes.com') /usr/lib/python3/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning) --- Logging error --- Traceback (most recent call last): File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit self.flush() File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush self.stream.flush() BrokenPipeError: [Errno 32] Broken pipe Call stack: File "/home/opsgenie/oec/scripts/actionExecutor.py", line 215, in <module> main() File "/home/opsgenie/oec/scripts/actionExecutor.py", line 169, in main timeout=timeout, verify=False) File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post return request('post', url, data=data, json=json, **kwargs) File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request return session.request(method=method, url=url, **kwargs) File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request resp = self.send(prep, **send_kwargs) File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send r = adapter.send(request, **kwargs) File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send timeout=timeout File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen chunked=chunked) File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 396, in _make_request httplib_response.length) Message: '%s://%s:%s "%s %s %s" %s %s' Arguments: ('https', 'jira.*******.com', 8443, 'POST', '/rest/api/2/issue/*****/comment', 'HTTP/1.1', 201, 432) --- Logging error --- Traceback (most recent call last): File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit self.flush() File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush self.stream.flush() BrokenPipeError: [Errno 32] Broken pipe Call stack: File "/home/opsgenie/oec/scripts/actionExecutor.py", line 215, in <module> main() File "/home/opsgenie/oec/scripts/actionExecutor.py", line 171, in main logging.info("Successfully executed at Jira") Message: 'Successfully executed at Jira' Arguments: () Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'> BrokenPipeError: [Errno 32] Broken pipe

----------------------------------

From my research, it appears to just be a connection issue with a socket, and it seems to be intermittent so I can't tell you how to reproduce, but it has been when acknowledging alerts.

**Comment by ahalac-atlassian** [comment]
Hi @DPatrickBoyd, you can track the progress about the issue from [this ticket](https://jira.atlassian.com/browse/OPSGENIE-1092)

**Comment by DPatrickBoyd** [comment]
two years later, and I set up another OEC and got this same error....looked for a solution and found my own ticket to an issue that no one has responded to!
